### ISSUE TITLE
Use SLF4J as logging API (+Logback)

### ISSUE THREAD

**Issue by ceefour** [opencog/relex#100]
[SLF4J](http://www.slf4j.org/faq.html#when) is the de facto logging API in Java, with more convenient API & enhanced performance than JUL or the old apache commons logging.

The actual logging backend is flexible, [Logback is great](http://logback.qos.ch/reasonsToSwitch.html), but SLF4J can work with Log4j and many others.

If accepted, you can assign to me.

**Comment by vsbogd** [comment]
Logging things are implemented so can be closed probably. 

Maven migration is a good thing but it should be a separate issue.

**Comment by linas** [comment]
closing per last comment
