### ISSUE TITLE
Relex removes dash "-" sign  

### ISSUE THREAD

**Issue by kkasunperera** [opencog/relex#133]
e.g. Her great-grandson is nicer than her great-granddaughter."
RelEx ouput following binary relationships but without '-' sign in terms "great-grandson" and "great-granddaughter"
"than(great grandson, great granddaughter)"
"_predadj(great grandson, nice)"
"_poss(great grandson, her)"
"_poss(great granddaughter, her)"
"_comparative(nice, great grandson)"

**Comment by linas** [comment]
Fixed in commit a2a65cfbe15b983569f9e24e69d71020a198beed
