### ISSUE TITLE
Plain text server crashed

### ISSUE THREAD

**Issue by leungmanhin** [opencog/relex#221]
It crashed when parsing this sentence from Simple English Wikipedia:

Military 162 killed, 947 wounded, 8 missing, 42 captured Police11 killed, 3 missing, 227 wounded 64 killed, 283 wounded, 3 missing, 12 captured South Ossetia: 150 killed (including volunteers), unknown number of wounded, 41 captured Abkhazia: 1 killed, 2 wounded South Ossetia: 162 according to Russia, 365 civilians and military according to South Ossetia Georgia: 224 civilians killed and 15 missing One foreign civilian killed and 3 wounded ----Refugees: At least 158,000 civilians displaced (including 30,000 South Ossetians that moved to North Ossetia, Russia; and 56,000 Georgians from Gori, Georgia and 15,000 Georgians from South Ossetia per UNHCR that moved to uncontested Georgia).

Got this error:
*** Error in `java': double free or corruption (out): 0x00007efbff979500 ***

**Comment by linas** [comment]
I cannot reproduce this. It was probably a link-grammar bug. Closing.
