### ISSUE TITLE
RelEx compact Format

### ISSUE THREAD

**Issue by parnika277** [opencog/relex#225]
Hi,
Can any one tell me how to change the output format that I m getting from relex (in Ubuntu).
I need the RelEx Compact output ( which gives the output in an xml format).
Thanks,
Parnika

**Comment by linas** [comment]
Try using WebFormat  -- Its another commandline tool -- see src/java/relex/WebFormat.java for details

**Comment by parnika277** [comment]
Hi,
How can I add other tabs( <sentence>, <links>) to WebFormat output? I want to add Stanford dependency.

**Comment by linas** [comment]
The stanford-style dependencies are generated by some extra rules, which are separately applied.  Look at the main relex code to see how to trigger the application of these rules; you would have to copy that code into WebFormat (i.e. to look for the --stanford flag, and if the flag is set, then apply the rules). Once the rules are applied, I believe that webformat will automatically print the resulting parses (snce it doesn't care how the parses were made).
