### ISSUE TITLE
Using WebFormat

### ISSUE THREAD

**Issue by parnika277** [opencog/relex#227]
Hi,
The WebFormat compact output is said to be usable for post-processing. How can I do that? I need the xml format output it gives, as an xml file for post-processing. If there is a xml file created then where is it located? Please help.
Thanks

**Comment by linas** [comment]
We do all of our post-processing in opencog. We do not use XML, we use scheme. At this time, we do not use the Web compact format for this.

I understand that you might not be interested in using OpenCog. That's OK.  Please don't use XML; almost any other possible data format is better than XML --so, for example JSON would be pretty good. XML is a disasterously bad format invented by idiots who flunked out of their comp-sci classes. It should be exterminated with extreme prejudice. Make the world a better place. Don't use it, don't allow your friends to use it.  If we work together, we can kill it.
