### ISSUE TITLE
Lemma of a word is missing sometimes

### ISSUE THREAD

**Issue by leungmanhin** [opencog/relex#236]
When parsing `Tom asks Roy how they are going to get the gold`, there is no lemma generated for the word `going`, this sometimes causes problems in R2L...

**Comment by linas** [comment]
Pull req #237 should fix this. Note, however, that the relex processing of this test sentence is bad, because there is no connection from the asking of the question, to the question itself.  I'll see if I can fix that real quick.

**Comment by linas** [comment]
pull req #238 actually produces more-or-less correct output, too.

**Comment by leungmanhin** [comment]
Thanks!!
