### ISSUE TITLE
Lemma is missing

### ISSUE THREAD

**Issue by leungmanhin** [opencog/relex#250]
There is no LemmaLink generates for one of the WordInstanceNode in these sentences:

No lemma for "allows" in:
`because love is directed toward others, it allows for the possibility that my critics were right and I was wrong.`

Sometimes no lemma for second "the" in:
`the main character, George Bailey, sacrificed everything he wanted in life for the people around him.`

**Comment by linas** [comment]
Bother words appear in the dict as part of an "idiom" -- "allows_for" and "the_people". As a result, the system cannot figure out what part of speech "allows" and "the" are supposed to be, and as a result, it fails to generate a lemma link.

There are thousands of idioms in the dictionary, all of them will have the same problem.

**Comment by linas** [comment]
After looking at this for a while, I am not sure what to do. I could "fake it" and generate a Lemma Link that is identical to the WordLink. What is the problem, if there is no lemma?

**Comment by leungmanhin** [comment]
I see, I was just playing with fuzzy matching and discovered this, missing lemma wouldn't cause any real problem as far as I know, I guess nothing needs to be changed for this, thanks!
