### ISSUE TITLE
problem in installing

### ISSUE THREAD

**Issue by myamyamya** [opencog/relex#255]
Not sure if this is the correct place to post this question but I am having trouble getting this repository working on an ubuntu environment. According to the https://github.com/opencog/relex/tree/master/install-scripts i ran the following codes:

git clone https://github.com/opencog/relex
cd relex
install-scripts/install-ubuntu-dependencies.sh

while executing the install script i get the following error:

Buildfile: build.xml does not exist!
Build failed
Buildfile: build.xml does not exist!
Build failed

When I inspected the code I noticed that every dependency was installed successfully. However, the ant build lines are not working.

if grep -q '^vagrant:' /etc/passwd; then
    cd /home/vagrant/relex
    sudo -u vagrant ant build
else
    ant build          <<<<<<< throws first error
fi

sudo ant install            <<<<<<<<< throws second error

Marked lines generate the errors and I am pretty sure there is a build.xml in the file. When I execute the following line to build the code, the output is like this:

$~/Downloads/relex$ ant build
Buildfile: /home/ppi/Downloads/relex/build.xml

build-subprojects:

init:

build-version:
     [echo] Building RelEx version 1.6.3
     [copy] Copying 1 file to /home/ppi/Downloads/relex/src/java/relex

look-for-owl:
     [echo] Will not build (optional) OWL output format; org.semanticweb.owl classes not found.

look-for-opennlp:
     [echo] Could not find (optional) OpenNLP-1.5 classes.

build-project:
     [echo] relex: /home/ppi/Downloads/relex/build.xml
    [mkdir] Created dir: /home/ppi/Downloads/relex/bin
    [javac] Compiling 77 source files to /home/ppi/Downloads/relex/bin
    [javac] /home/ppi/Downloads/relex/src/java/relex/Server.java:383: error: cannot find symbol
    [javac] 		LinkGrammar.doFinalize();
    [javac] 		           ^
    [javac]   symbol:   method doFinalize()
    [javac]   location: class LinkGrammar
    [javac] /home/ppi/Downloads/relex/src/java/relex/parser/LocalLGParser.java:78: error: cannot find symbol
    [javac] 		LinkGrammar.doFinalize();
    [javac] 		           ^
    [javac]   symbol:   method doFinalize()
    [javac]   location: class LinkGrammar
    [javac] 2 errors

BUILD FAILED
/home/ppi/Downloads/relex/build.xml:90: Compile failed; see the compiler error output for details.

Total time: 1 second

So, the error is related to LinkGrammar, yet I do not have any prior experience about this library. Can anybody help me overcome this problem?

Any single help is appreciated.
Thx in advance.

**Comment by linas** [comment]
The missing symbol `doFinalize` only appears in the very newest link-grammar, version 5.3.15 which was published only yesterday, probably after you opened this bug report.  Try again, this time it should work.

**Comment by linas** [comment]
closing, believed fixed.
