### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/relex#256]
@linas, it looks like this fix 2c18f5a89cacdfd1e4a174652afd7c8089304270 is leading to errors in the HR HEAD stack. 

See https://github.com/hansonrobotics/HEAD/issues/709

**Comment by linas** [comment]
yeah, that's strange. For languages other than english, it was too short by one word.  Investigating

**Comment by linas** [comment]
OK, should be fixed in 301695ce024b7db150009b93d99f92299b30dbbe

**Comment by linas** [comment]
closing, believed fixed.
