### ISSUE TITLE
split_sentences.pl does not work for Project Guttenberg text files

### ISSUE THREAD

**Issue by inflector** [opencog/relex#257]
The file: 'split-sentences.pl' does not correctly concatenate lines that break mid-sentence. It also does not handle Windows `<return><newline>` line endings well as it assumes the unix-style `<newline>` only endings.

https://github.com/opencog/relex/blob/master/src/split-sentences/split-sentences.pl

This is an important limitation / feature / bug because this file is used extensively as part of the input process for the current opencog/nlp/learning pipeline. The sentence splitting tool should either include more specific documentation for the expected form of the input file, or it needs to be adapted to handle more diverse inputs, including the fairly common format for public domain books on Project Guttenberg.

Since the comments on language learning discouraged the use of wikipedia as a poor choice for learning grammar, I used a simple text file of Pride and Prejudice from Project Guttenberg: https://www.gutenberg.org/files/1342/1342-0.txt

Here are the first few opening paragraphs:
```
PRIDE AND PREJUDICE

By Jane Austen



Chapter 1


It is a truth universally acknowledged, that a single man in possession
of a good fortune, must be in want of a wife.

However little known the feelings or views of such a man may be on his
first entering a neighbourhood, this truth is so well fixed in the minds
of the surrounding families, that he is considered the rightful property
of some one or other of their daughters.

“My dear Mr. Bennet,” said his lady to him one day, “have you heard that
Netherfield Park is let at last?”
```
Notice the line breaks in the text file. For example, after "in possession" and before "of a good fortune".

Running the recommended sentence splitter:
`cat pride.txt | split-sentences/split-sentences.pl -l en > pride_split.txt`

Results in:
```
PRIDE AND PREJUDICE
<P>
By Jane Austen
<P>
Chapter 1
<P>
It is a truth universally acknowledged, that a single man in possession
 of a good fortune, must be in want of a wife.
<P>
However little known the feelings or views of such a man may be on his
 first entering a neighbourhood, this truth is so well fixed in the minds
 of the surrounding families, that he is considered the rightful property
 of some one or other of their daughters.
<P>
“My dear Mr. Bennet,” said his lady to him one day, “have you heard that
 Netherfield Park is let at last?”
```
So the sentence splitter correctly removes extra lines but it **does not consolidate lines that break before sentence ends in the original input**. So the lines in the output are sentence fragments and not complete sentences. Comments in language learning scripts like /nlp/learn/run/submit-one.pl like:

```
# Submit a collection of sentences, one sentence at a time, to the
# cogserver located on host ARGV[0] and port ARGV[1].  The sentences
# are read from standard input, and must be arranged with one sentence
# per line.
```

indicate that the full sentence should be completed in one single line before the line break. So a proper splitting of the input text would be:
```
PRIDE AND PREJUDICE
<P>
By Jane Austen
<P>
Chapter 1
<P>
It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.
<P>
However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.
<P>
“My dear Mr. Bennet,” said his lady to him one day, “have you heard that Netherfield Park is let at last?”
<P>
```

The addition of the following after line 115 in fixes the problem for this case, but may break other workflows so i have not submitted a pull request for this until we can discuss the best way to handle this issue.

https://github.com/opencog/relex/blob/master/src/split-sentences/split-sentences.pl#L109-L115

```
	# Clean up single newlines that are not also paragraph breaks.
	$text =~ s/\n(?=[^\n])/ /g;
```

Further, to fix this so it works for Windows-style `<return><newline>` line endings one can insert the following line to remove the unnecessary `<return>` characters before any of the other processing at line 109:

```
	# Remove any spurious Windows return characters because Windows ends 
	# lines with '\r\n'.
	$text =~ s/\r//g;
```

**Comment by linas** [comment]
Closing, the splitters no longer live with relex, (they've moved to opencog/nlp/learn) and anyway are a bit different these days.
