### ISSUE TITLE
error in compiling NLGInputView java file

### ISSUE THREAD

**Issue by simonmekit** [opencog/relex#264]
I'm trying to build relex from inside docker using 'octool'. here are some syntax errors i found: 
1. relex/src/java/relex/output/NLGInputView.java:109: error: unmappable character for encoding ASCII
 - I removed the last String "n’t" 
2. closing brace at line 128
 - I removed it and closed at 170
3. relex/src/java/relex/output/NLGInputView.java:223: error: class, interface, or enum expected

1 and 2 seems corrected but still 3 remains error
any idea?

**Comment by vsbogd** [comment]
Hi @simonmekit, does my advice above resolve the issue?

**Comment by simonmekit** [comment]
Hi @vsbogd, thanks for the advice. 
for the first case removing the last token "n't" from NLGInputView.java file solved the issue.
the closing brace issue is fine as it is in the current java file, no need to remove braces.

**Comment by vsbogd** [comment]
Closing it as it looks solved.

**Comment by vsbogd** [comment]
Sorry, looks like I cannot close it :-) So @simonmekit or @linas, could you please close it.
