### ISSUE TITLE
Missing java library-slf4j 

### ISSUE THREAD

**Issue by Kidist-Abraham** [opencog/relex#273]
While building relex on rapberryPi, I encountered an error of "package org.slf4j does not exist" even after i add the " slf4j-1.7.25.jar" file in to /usr/share/java folder.

**Comment by vsbogd** [comment]
Hi @Kidist-Abraham, what kind of Linux do you use on Raspberry PI? If it is Ubuntu you can use ```sudo apt-get install libslf4j-java liblogback-java``` to fix setup.

Manually you can add following symlinks to make it work:
```
${PREFIX}/slf4j-api.jar -> ${PREFIX}/slf4j-api-1.7.25.jar
${PREFIX}/logback-core.jar -> ${PREFIX}/logback-core-1.2.3.jar
${PREFIX}/logback-classic.jar -> ${PREFIX}/logback-classic-1.2.3.jar
```

You can also use ```maven``` to build RelEx without managing dependencies by hand. But in such case you need manually prepare run environment. Automatic run environment preparation is raised as https://github.com/opencog/relex/issues/267.

**Comment by Kidist-Abraham** [comment]
Hello @vsbogd , Thank you for the help. The OS is raspbian.  I manually added the library and it runs. But I was thinking to add the maven build to the installation script. I will check that out.

**Comment by vsbogd** [comment]
Just found recently that Raspbian is based on Debian, so at least on last version which is based on Debian Stretch ```sudo apt-get install libslf4j-java liblogback-java``` should work properly.

**Comment by Kidist-Abraham** [comment]
okay. tnx
